os: linux
sudo: false
language: python

cache:
  - pip
  - pip3

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

install:
  - pip install -r requirements.txt
  - pip install codecov pytest-cov

script: pytest --cov=./ ./test.py

after_success:
   - codecov
   - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false